
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      labels:
        app: helm-controller
    spec:
      automountServiceAccountToken: true
      containers:
        - name: helm-controller
          image: r.gamewarden.io/base/flux-helm-controller:1.1.0-r0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: kustomize-controller
  template:
    metadata:
      labels:
        app: kustomize-controller
    spec:
      automountServiceAccountToken: true
      containers:
        - name: kustomize-controller
          image: r.gamewarden.io/base/flux-kustomize-controller:1.4.0-r0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: notification-controller
  template:
    metadata:
      labels:
        app: notification-controller
    spec:
      automountServiceAccountToken: true
      containers:
        - name: notification-controller
          image: r.gamewarden.io/base/flux-notification-controller:1.4.0-r0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: source-controller
  template:
    metadata:
      labels:
        app: source-controller
    spec:
      automountServiceAccountToken: true
      containers:
        - name: source-controller
          image: r.gamewarden.io/base/flux-source-controller:1.4.1-r0
